echo "------------------------------------------------------------------------------------------------------------------------"
echo "This script shows you where you have the old php_flag and php_value commands in your .htaccess files."
echo "It will NOT delete these commands, nor will it change your php.ini file."
echo "For safety, please do the changes manually and after a full backup."
echo "------------------------------------------------------------------------------------------------------------------------"
echo -en "\n\n"
echo "Occurances of the words \"php_flag\" or \"php_value\" under www"
echo "The format is:"
echo "path/to/file:line_number <line>"
grep -Rnw 'www' -e "php_flag" 
grep -Rnw 'www' -e "php_value"
echo -en "\n\n"
